return {
	"gui_entry_point",
	"gui_main",
	-- "all_seeing_eye",
	-- "clear_projectiles",
	-- "convenient_wand",
	-- "creative_mode_flight",
	-- "damage_info",
	-- "dummy_transforming",
	-- "hp_fixer",
	-- "input",
	-- "no_annoying_effects",
	-- "no_polymorphing",
	-- "no_recoil",
	-- "no_weather",
	-- "terrain_spell_lab",
	-- "player",
	-- "protection_all",
	-- "shortcuts",
	-- "shot_effects",
	-- "spell_api",
	-- "spell_box",
	-- "spell_group_box",
	-- "spell_picker",
	-- "target_dummy",
	-- "twwe_effect",
	-- "unlimited_spells",
	-- "wand_box",
	-- "wand_clear",
	-- "wand_edit_panel",
	-- "wand_no_shooting",
	-- "wand_picker",
	-- "wand_ready",
}
